### ISSUE TITLE
几点建议

### ISSUE THREAD

**Issue by Thare-Lam** [youmi/alertover-uservoice#1]
1.客户端消息通知希望能支持左滑删除.
2.进入应用能自动获取新消息.
3.网页端添加成员希望能开放接口,这样添加多个用户就比较方便.

**Comment by ruitao** [comment]
1. 消息会自动过期的，就我们的使用过程中来看，删掉的必要性不大
2. 这个不知道你用的是哪个版本，现在都是会自动获取新信息的
3. 这个已经在群里沟通过，建议用微信消息模板：）

**Comment by Thare-Lam** [comment]
组织里的普通成员和客人也有权限修改发送源和接收源的成员吗?

**Comment by Thare-Lam** [comment]
IOS和Android端都是0.2.2   都必须下拉才能获取新消息   推送是可以收到的

**Comment by ruitao** [comment]
> 组织里的普通成员和客人也有权限修改发送源和接收源的成员吗?

不可以，如果你发现可以，可能是bug，我们看看

> IOS和Android端都是0.2.2 都必须下拉才能获取新消息 推送是可以收到的

已经让客户端的同事看看

**Comment by Thare-Lam** [comment]
刚又看了以下  一个客人账号的权限和拥有者的权限确实是一样的

**Comment by ruitao** [comment]
@Thare-Lam 权限问题已fix
