### ISSUE TITLE
Chrome Plugin - Clear Notifications

### ISSUE THREAD

**Issue by ryanerwin** [youmi/alertover-uservoice#5]
When using the Alertover Chrome plugin, there is no function for clearing notifications.
The Android app allows deleting individual messages, but using the Chrome plugin there doesn't seem to be any way to clear old messages. Old messages just stack up more and more...

![image](https://cloud.githubusercontent.com/assets/2156415/20878157/356ccace-bb08-11e6-876f-5b18e837deac.png)

**Comment by LoeiFy** [comment]
@ryanerwin thx

v0.3.1 support clear the messages, please checkout the new version

https://chrome.google.com/webstore/detail/alertover/cgcgodonijnlgljfdbiicdccnldpdgia

**Comment by ryanerwin** [comment]
@LoeiFy i've updated to the new version and it's working great so far 👍
